products = [
    # GFUEL Energy Tubs
    ('gfuel_blue_ice.png', 'Blue Ice'),
    ('gfuel_watermelon.png', 'Watermelon'),
    ('gfuel_tropical_rain.png', 'Tropical Rain'),
    ('gfuel_sour_cherry.png', 'Sour Cherry'),
    ('gfuel_rainbow_sherbet.png', 'Rainbow Sherbet'),
    ('gfuel_lemon_lime.png', 'Lemon Lime'),
    ('gfuel_strawberry_shortcake.png', 'Strawberry Shortcake'),
    ('gfuel_bahama_mama.png', 'Bahama Mama'),
    ('gfuel_hype_sauce.png', 'Hype Sauce'),
    ('gfuel_pewdiepie.png', 'PewDiePie'),
    # GFUEL Shaker Cups
    ('gfuel_pewdiepie_shaker.png', 'PewDiePie Shaker'),
    ('gfuel_faze_clan_shaker.png', 'FaZe Clan Shaker'),
    ('gfuel_glow_shaker.png', 'Glow Shaker'),
    ('gfuel_winter_white_shaker.png', 'Winter White Shaker'),
    ('gfuel_pink_drip_shaker.png', 'Pink Drip Shaker'),
    ('gfuel_blacked_out_shaker.png', 'Blacked Out Shaker'),
    ('gfuel_team_kaliber_shaker.png', 'Team Kaliber Shaker'),
    ('gfuel_miami_nights_shaker.png', 'Miami Nights Shaker'),
    ('gfuel_sonic_shaker.png', 'Sonic Shaker'),
    ('gfuel_golden_apple_pear_shaker.png', 'Golden Apple Pear Shaker'),
    # GFUEL Starter Packs
    ('gfuel_starter_kit_blue.png', 'Starter Kit Blue'),
    ('gfuel_starter_kit_red.png', 'Starter Kit Red'),
    ('gfuel_starter_kit_green.png', 'Starter Kit Green'),
    ('gfuel_starter_kit_pink.png', 'Starter Kit Pink'),
    ('gfuel_starter_kit_black.png', 'Starter Kit Black'),
    ('gfuel_starter_kit_white.png', 'Starter Kit White'),
    ('gfuel_starter_kit_orange.png', 'Starter Kit Orange'),
    ('gfuel_starter_kit_purple.png', 'Starter Kit Purple'),
    ('gfuel_starter_kit_yellow.png', 'Starter Kit Yellow'),
    ('gfuel_starter_kit_teal.png', 'Starter Kit Teal'),
]
